name = "apieverything"
main = "worker.js"
compatibility_date = "2026-06-10"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "everything.rellia.org", custom_domain = true }
]

[observability]
enabled = true

[assets]
directory = "."
binding = "ASSETS"
not_found_handling = "single-page-application"

[vars]
SUPABASE_URL = "https://kavodsarpdvzmaqrkunv.supabase.co"

[ai]
binding = "AI"

[env.staging]
name = "apieverything-staging"
routes = [
  { pattern = "everything-staging.rellia.org", custom_domain = true }
]

[env.staging.vars]
SUPABASE_URL = "https://kavodsarpdvzmaqrkunv.supabase.co"

[env.staging.ai]
binding = "AI"
